
FIND_PATH(FASTINF_INCLUDE_DIR lbDefinitions.h)
FIND_LIBRARY(FASTINF_LOOPY_INF_LIBRARY  NAMES libLoopyInf ) 

# handle the QUIETLY and REQUIRED arguments and set FASTINF_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(FASTINF DEFAULT_MSG 
FASTINF_INCLUDE_DIR  
FASTINF_LOOPY_INF_LIBRARY             
)
        
IF(FASTINF_FOUND)
   SET(FASTINF_LIBRARIES ${FASTINF_LOOPY_INF_LIBRARY} )
ELSE()
SET(FASTINF_INCLUDE_DIR                   FASTINF_INCLUDE_DIR-NOTFOUND)
SET(FASTINF_LOOPY_INF_LIBRARY             FASTINF_LOOPY_INF_LIBRARY-NOTFOUND)
ENDIF()
    
