
SET(OSI_ROOT_DIR "" CACHE PATH "OSI root directory")

# FIND OSI LIB,UTILS LIB AND INCLUDES
FIND_PATH(OSI_INCLUDE_DIR coin/OsiSolverInterface.hpp
  HINTS ${OSI_ROOT_DIR}/include
)

FIND_LIBRARY(OSI_UTILS_LIBRARY
  NAMES CoinUtils libCoinUtils
  HINTS ${OSI_ROOT_DIR}/lib/coin
  HINTS ${OSI_ROOT_DIR}/lib
)
FIND_LIBRARY(OSI_LIBRARY
  NAMES Osi libOsi
  HINTS ${OSI_ROOT_DIR}/lib/coin
  HINTS ${OSI_ROOT_DIR}/lib
)

#######################################################
# SOLVERS 
#######################################################

#CLP
FIND_PATH(OSI_CLP_INCLUDE_DIR coin/OsiClpSolverInterface.hpp
  HINTS ${OSI_ROOT_DIR}/include
)
FIND_LIBRARY(CLP_LIBRARY
  NAMES OsiClp libClp
  HINTS ${OSI_ROOT_DIR}/lib/coin
  HINTS ${OSI_ROOT_DIR}/lib
)
FIND_LIBRARY(OSI_CLP_LIBRARY
  NAMES OsiOsiClp libOsiClp
  HINTS ${OSI_ROOT_DIR}/lib/coin
  HINTS ${OSI_ROOT_DIR}/lib
)

#GLPK
find_package(GLPK)

FIND_PATH(OSI_GLPK_INCLUDE_DIR coin/OsiGlpkSolverInterface.hpp
  HINTS ${OSI_ROOT_DIR}/include
)
FIND_LIBRARY(OSI_GLPK_LIBRARY
  NAMES OsiOsiGlpk libOsiGlpk
  HINTS ${OSI_ROOT_DIR}/lib/coin
  HINTS ${OSI_ROOT_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSI DEFAULT_MSG
  OSI_INCLUDE_DIR
  OSI_UTILS_LIBRARY
  OSI_LIBRARY
)

IF(OSI_FOUND)
   SET(OSI_BASE_INCLUDE_DIRS ${OSI_INCLUDE_DIR})
   SET(OSI_BASE_LIBRARIES "${OSI_LIBRARY};${OSI_UTILS_LIBRARY}")
   #CLP
   IF(CLP_LIBRARY AND OSI_CLP_LIBRARY AND OSI_GLPK_INCLUDE_DIR)
      SET(OSI_CLP_INCLUDE_DIRS "${OSI_GLPK_INCLUDE_DIR}")
      SET(OSI_CLP_LIBRARIES "${OSI_CLP_LIBRARY};${CLP_LIBRARY}")
      SET(OSI_CLP_FOUND True)
   ELSE()
      SET(OSI_CLP_FOUND False)
   ENDIF()
   #GLPK
   IF(GLPK_FOUND AND OSI_GLPK_LIBRARY AND OSI_GLPK_INCLUDE_DIR)
      SET(OSI_GLPK_INCLUDE_DIRS "${GLPK_INCLUDE_DIRS};${OSI_GLPK_INCLUDE_DIR})
      SET(OSI_GLPK_LIBRARIES "${OSI_GLPK_LIBRARY};${GLPK_LIBRARIES}")
      SET(OSI_GLPK_FOUND True)
   ELSE()
      SET(OSI_GLPK_FOUND False)
   ENDIF()
   #combine all solver libs (clp,glpk,....)
   SET (OSI_SOLVER_LIBRARIES "${OSI_CLP_LIBRARIES};${OSI_GLPK_LIBRARIES}")
   #combine all libs  
   SET(OSI_LIBRARIES "${OSI_SOLVER_LIBRARIES};${OSI_BASE_LIBRARIES}")
ENDIF(OSI_FOUND)

MARK_AS_ADVANCED(
  OSI_INCLUDE_DIR
  OSI_UTILS_LIBRARY
  OSI_LIBRARY
)
