
SET(COIN_ROOT_DIR "" CACHE PATH "COIN root directory")

FIND_PATH(COIN_INCLUDE_DIR coin/CoinUtilsConfig.h
  HINTS ${COIN_ROOT_DIR}/include
)

FIND_PATH(COIN_OSI_INCLUDE_DIR coin/OsiSolverInterface.hpp
  HINTS ${COIN_ROOT_DIR}/include
)

FIND_PATH(COIN_OSI_GLPK_INCLUDE_DIR coin/OsiGlpkSolverInterface.hpp
  HINTS ${COIN_ROOT_DIR}/include
)



FIND_LIBRARY(COIN_COIN_UTILS_LIBRARY
  NAMES CoinUtils libCoinUtils
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)
FIND_LIBRARY(COIN_OSI_LIBRARY
  NAMES Osi libOsi
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)


FIND_LIBRARY(COIN_ZLIB_LIBRARY
  NAMES z libz
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)
FIND_LIBRARY(COIN_BZ2_LIBRARY
  NAMES bz2 libbz2
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)


FIND_LIBRARY(COIN_OSI_GLPK_LIBRARY
  NAMES OsiOsiGlpk libOsiGlpk
  HINTS ${COIN_ROOT_DIR}/lib/coin
  HINTS ${COIN_ROOT_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(COIN DEFAULT_MSG
  COIN_INCLUDE_DIR
  COIN_OSI_INCLUDE_DIR
  COIN_OSI_GLPK_INCLUDE_DIR
  COIN_OSI_GLPK_LIBRARY
  COIN_COIN_UTILS_LIBRARY
  COIN_OSI_LIBRARY
)

IF(COIN_FOUND)
  SET(COIN_INCLUDE_DIRS ${COIN_INCLUDE_DIR})
  SET(OSI_INCLUDE_DIRS ${COIN_OSI_INCLUDE_DIR} )
  SET(OSI_GLPK_INCLUDE_DIRS ${COIN_OSI_GLPK_INCLUDE_DIR})
  SET(COIN_GLPK_LIBRARIES "${COIN_OSI_GLPK_LIBRARY}")
  SET(COIN_OSI_LIBRARIES "${COIN_OSI_LIBRARY};${COIN_COIN_UTILS_LIBRARY};${COIN_ZLIB_LIBRARY};${COIN_BZ2_LIBRARY}")
ENDIF(COIN_FOUND)

MARK_AS_ADVANCED(
  COIN_INCLUDE_DIR
  COIN_OSI_INCLUDE_DIR
  COIN_OSI_GLPK_INCLUDE_DIR
  COIN_COIN_UTILS_LIBRARY
  COIN_OSI_LIBRARY
)

IF(COIN_FOUND)


ENDIF(COIN_FOUND)
